### ISSUE TITLE
EPIC: As a PO I want should have requirements implemented

### ISSUE THREAD

**Issue by StijnKing** [SEP-TU-e-2024/website#119]
## Description
A list to keep track of which should haves are finished and which ones are still being worked on. This should provide an overview of how far into the project we are. A should have is done once it is implemented such that it can be tested. No user stories should be left that involve the requirement.

## Acceptance Criteria
User Account Registration
- [x] URF 1.1
- [x] URF 1.2
- [ ] URF 1.3 (only username, no institution)
- [x] URF 1.7 (atm this is password, email, username)

Specified problem requirements
- [ ] URF 4.3 (actual description needs to be added)

Problem occurrence requirements
- [x] URF 5.4

Configuration requirements
All specified problems are
- [ ] URF 6.1 (open or closed)
- [x] URF 6.2 (competition or scientific type)
All submissions are
- [ ] URF 6.3 (downloadable or not for all users)
- [ ] URF 6.4 (starred or not)

Problem instance requirements
- [ ] URF 7.2

Submission requirements
- [ ] URF 8.2
- [ ] URF 8.3
- [ ] URF 8.7

Code submission requirements
- [ ] URF 9.1

Evaluation settings requirements
- [ ] URF 11.5
- [ ] URF 11.6

Evaluation requirements
- [ ] URF 12.3
- [ ] URF 12.4
- [ ] URF 12.5
- [ ] URF 12.6
- [ ] URF 12.7
- [ ] URF 12.8
- [ ] URF 12.9
- [ ] URF 12.12

Problem occurrence leaderboard requirements
- [ ] URF 15.2
- [ ] URF 15.8

Problem instance leaderboard requirements
- [ ] URF 16.2
- [ ] URF 16.6
- [ ] URF 16.8
- [ ] URF 16.12

Miscellaneous requirements
- [ ] URF 18.4

Security constraints requirement list
- [ ] URC 1.4
- [ ] URC 1.6
- [ ] URC 1.8

Hardware and Software constraints requirement list
- [x] URC 2.3
- [ ] URC 2.5

Usability constraints requirement list
- [ ] URC 3.3
