### ISSUE TITLE
EPIC: As a customer I want to be prepared for the Acceptance Test

### ISSUE THREAD

**Issue by StijnKing** [SEP-TU-e-2024/website#131]
The customer has to do an acceptance test plan to verify that the software works as expected.

For this we need to:
- [ ] Inform the customer on any azure requirements
- [ ] Prepare a guide (textual or visual) for the customer on how to setup the project on azure
- [ ] Write the ATP but this is a separate EPIC
