### ISSUE TITLE
EPIC: As a PO I want all must have requirements implemented

### ISSUE THREAD

**Issue by StijnKing** [SEP-TU-e-2024/website#55]
## Description
A list to keep track of which must haves are finished and which ones are still being worked on. This should provide an overview of how far into the project we are. A must have is done once it is implemented such that it can be tested. No user stories should be left that involve the checked of requirements.

## Acceptance Criteria
User Account Login
- [x] URF 2.1 
- [x] URF 2.2
- [x] URF 2.3
- [x] URF 2.4
- [x] URF 2.5

Specified problem requirements
- [x] URF 4.1 #3 
- [x] URF 4.3 #111 and #114

Problem occurrence requirements
- [x] URF 5.1 #90
- [x] URF 5.2 #90
- [x] URF 5.3
- [x] URF 5.6

Configuration requirement
- [x] URF 6.2 (competition or scientific type)

Problem instance requirements
- [x] URF 7.3 #115

Submission requirements
- [x] URF 8.1
- [x] URF 8.4 #92
- [x] URF 8.5
- [x] URF 8.8 #96

Code submission requirements
- [x] URF 9.2 (after submission start code submission evaluation) #103 

Evaluation requirements
- [x] URF 12.1 (computing metrics should be shown on actual problem)
- [x] URF 12.2 #94 and #106
- [x] URF 12.10 #91

Code evaluation requirements
- [x] URF 13.1 #107
- [x] URF 13.2 #93
- [x] URF 13.3 #49

Problem occurrence leaderboard requirements
- [x] URF 15.1 #114
- [x] URF 15.3 #102 
- [x] URF 15.4 #100 (Needs #108)
- [x] URF 15.5 #98 and #109 
- [x] URF 15.7 (Needs #96) #99
- [x] URF 15.9 #97
- [x] URF 15.10 #113

Problem instance leaderboard requirements
- [x] URF 16.1 #111
- [x] URF 16.3 #102 
- [x] URF 16.4 #112
- [x] URF 16.5 #98
- [x] URF 16.7 #99
- [x] URF 16.9 #97

Security constraints requirement list
- [x] URC 1.1
- [x] URC 1.2
- [x] URC 1.3

Hardware and Software constraints requirement list
- [x] URC 2.1
- [x] URC 2.2 #89 
- [x] URC 2.4

Usability constraints requirement list
- [x] URC 3.1
- [x] URC 3.2 (make easier and documented) #110
